var annotated =
[
    [ "FFXCAggregateTarget", "interface_f_f_x_c_aggregate_target.html", null ],
    [ "FFXCBuildConfiguration", "interface_f_f_x_c_build_configuration.html", "interface_f_f_x_c_build_configuration" ],
    [ "FFXCBuildFile", "interface_f_f_x_c_build_file.html", "interface_f_f_x_c_build_file" ],
    [ "FFXCBuildPhase", "interface_f_f_x_c_build_phase.html", "interface_f_f_x_c_build_phase" ],
    [ "FFXCConfigurableObject", "interface_f_f_x_c_configurable_object.html", "interface_f_f_x_c_configurable_object" ],
    [ "FFXCConfigurationList", "interface_f_f_x_c_configuration_list.html", "interface_f_f_x_c_configuration_list" ],
    [ "FFXCContainerItemProxy", "interface_f_f_x_c_container_item_proxy.html", "interface_f_f_x_c_container_item_proxy" ],
    [ "FFXCCopyFilesBuildPhase", "interface_f_f_x_c_copy_files_build_phase.html", "interface_f_f_x_c_copy_files_build_phase" ],
    [ "FFXCExplicitFileReference", "interface_f_f_x_c_explicit_file_reference.html", "interface_f_f_x_c_explicit_file_reference" ],
    [ "FFXCFileObject", "interface_f_f_x_c_file_object.html", "interface_f_f_x_c_file_object" ],
    [ "FFXCFrameworksBuildPhase", "interface_f_f_x_c_frameworks_build_phase.html", null ],
    [ "FFXCGroup", "interface_f_f_x_c_group.html", "interface_f_f_x_c_group" ],
    [ "FFXCHeadersBuildPhase", "interface_f_f_x_c_headers_build_phase.html", null ],
    [ "FFXCKnownFileReference", "interface_f_f_x_c_known_file_reference.html", "interface_f_f_x_c_known_file_reference" ],
    [ "FFXCNamedBuildPhase", "interface_f_f_x_c_named_build_phase.html", "interface_f_f_x_c_named_build_phase" ],
    [ "FFXCNamedFileReference", "interface_f_f_x_c_named_file_reference.html", "interface_f_f_x_c_named_file_reference" ],
    [ "FFXCNamedGroup", "interface_f_f_x_c_named_group.html", "interface_f_f_x_c_named_group" ],
    [ "FFXCNativeTarget", "interface_f_f_x_c_native_target.html", "interface_f_f_x_c_native_target" ],
    [ "FFXCObject", "interface_f_f_x_c_object.html", "interface_f_f_x_c_object" ],
    [ "FFXCObjectsManager", "interface_f_f_x_c_objects_manager.html", "interface_f_f_x_c_objects_manager" ],
    [ "FFXCPathGroup", "interface_f_f_x_c_path_group.html", "interface_f_f_x_c_path_group" ],
    [ "FFXCProject", "interface_f_f_x_c_project.html", "interface_f_f_x_c_project" ],
    [ "FFXCProjectFile", "interface_f_f_x_c_project_file.html", "interface_f_f_x_c_project_file" ],
    [ "FFXCProjectUIDGenerator", "interface_f_f_x_c_project_u_i_d_generator.html", null ],
    [ "FFXCResourcesBuildPhase", "interface_f_f_x_c_resources_build_phase.html", null ],
    [ "FFXCShellScriptBuildPhase", "interface_f_f_x_c_shell_script_build_phase.html", "interface_f_f_x_c_shell_script_build_phase" ],
    [ "FFXCSourcesBuildPhase", "interface_f_f_x_c_sources_build_phase.html", null ],
    [ "FFXCTarget", "interface_f_f_x_c_target.html", "interface_f_f_x_c_target" ],
    [ "FFXCTargetDependency", "interface_f_f_x_c_target_dependency.html", "interface_f_f_x_c_target_dependency" ],
    [ "FFXCVariantGroup", "interface_f_f_x_c_variant_group.html", null ]
];